### ISSUE TITLE
[PROPOSAL] Input / Output for ViewModel

### ISSUE THREAD

**Issue by NghiaTranUIT** [khoi/SimpleBudget#22]
## Why
It's so straight-forward to distinguish what is the input and output stream from ViewModel when the ViewModel eventually becomes bigger.

## Problem for current approach
Let take this [WalletListViewModel](https://github.com/khoi/SimpleBudget/blob/master/SimpleBudget/Scene/WalletList/WalletListViewModel.swift) as a good example

1. Although that the Action means the input. It takes me more than 1 second to determine what is the input/output. 
https://github.com/khoi/SimpleBudget/blob/b34ae0899594b918d625b413d5d9586b6a2824b4/SimpleBudget/Scene/WalletList/WalletListViewModel.swift#L12-L20

2. Those output Observables is mutable
https://github.com/khoi/SimpleBudget/blob/b34ae0899594b918d625b413d5d9586b6a2824b4/SimpleBudget/Scene/WalletList/WalletListViewModel.swift#L12-L13

3. The Init tends to grow bigger as long as the complexity of the app.
Like this 
https://github.com/NghiaTranUIT/Unofficial-Uber-macOS/blob/5a52e23f087c9d005a84b0af8b8568070321782f/UberGoCore/UberGoCore/SearchViewModel.swift#L62-L156

### 1. ViewModelType
It's general protocol, which should be adopted by all ViewModels in the app.
```swift
protocol ViewModelType {
  associatedtype Input
  associatedtype Output

  func transform(_ input: Input) -> Output
}
```
### Input and Output struct
By introducing the `Input` and `Output` struct, which are internal components of WalletListViewModel, we can encapsulate all streams appropriately.
```swift
  struct Input {
    let textFieldEnableObs: Observable<Bool> // Example
    let navigateToTransactionList: Observable<Wallet>
    let removeWallet: Observable<Wallet>
  }

  struct Output {
    let wallets: Observable<[Wallet]>
    let navigateToCreateWalletAction: CocoaAction
    let somethingObs: Observable<Int> // Example
  }
```
It obviously increase the readability of the codebase.

### WalletViewModel
```swift
// Adopt new ViewModelType
final class WalletListViewModel: Stepper, ViewModelType {

  struct Input {
    let textFieldEnableObs: Observable<Bool> // Example
    let navigateToTransactionList: Observable<Wallet>
    let removeWallet: Observable<Wallet>
  }

  struct Output {
    let wallets: Observable<[Wallet]>
    let navigateToCreateWalletAction: CocoaAction
    let somethingObs: Observable<Int> // Example
  }

  // MARK: - Variable
  private let budgetService: PersistenceServiceType
  private let disposeBag = DisposeBag()

  // The init is tiny as possible
  init(budgetService: PersistenceServiceType) { 
    self.budgetService = budgetService
  }

  // At this time, we actually transform the signal, which we desire
  func transform(_ input: WalletListViewModel.Input) -> WalletListViewModel.Output {

    // Transform enable input
    let outputObs = input.textFieldEnableObs.map { $0 ? 100 : 0}

    // Create Action
    let action = CocoaAction { [unowned self] in
        self.step.accept(AppStep.createWallet)
        return .empty()
    }

    // Remove Wallet
    input.removeWallet
      .flatMapLatest { [unowned self] (budget) -> Observable<Void> in
        self.budgetService.deleteWallet(id: budget.id)
      }
      .subscribe()
      .disposed(by: disposeBag)

    // Transaction List
    input.navigateToTransactionList
      .subscribe(onNext: { [unowned self] wallet in
        self.step.accept(AppStep.transactionList(walletId: wallet.id))
      })
      .disposed(by: disposeBag)

    // Return
    return Output(wallets: budgetService.wallets(),
                  navigateToCreateWalletAction: action,
                  somethingObs: outputObs)
  }
}
```
### View Controller
```swift
  func setupBinding() {

   // This time, we pass all inputs. 
    let input = WalletListViewModel.Input(textFieldEnableObs: .just(true),
                                          navigateToTransactionList: tableView.rx.modelSelected(Wallet.self).asObservable(),
                                          removeWallet: tableView.rx.modelDeleted(Wallet.self).asObservable())

    // Then Get the output stream
    // to map to UI
    let output = viewModel.transform(input)

    output
      .wallets
      .map { [SectionOfWallet(header: "Budget", items: $0)] }
      .bind(to: tableView.rx.items(dataSource: dataSources))
      .disposed(by: rx.disposeBag)

    addBudgetBarButtonItem.rx.action = output.navigateToCreateWalletAction
  }
```

## Result
1. The initializer of ViewModel is tiny as possible.
2. Distinguish what is the Input and Output stream of ViewModel
3. Strengthen the readability.
4. Get rid of Action (maybe)
5. ...

## What's else
If we adopt this technique, we should refactor all viewModels in the app as well, such as `CreateWalletViewModel`, `TransactionListViewModel`.

How do you guys think 😄 ? Feels free to come up your idea 👍 👨‍💻

**Comment by dangthaison91** [comment]
@NghiaTranUIT  What if your `ViewModel.Input` have many inputs?

**Comment by khoi** [comment]
overall I like the idea. Let's do this

@dangthaison91 I don't get it, please collaborate

**Comment by NghiaTranUIT** [comment]
@dangthaison91 If the app grows bigger, it's obvious that all inputs are isolated in the `Input` struct. So it increase the ViewModel's readability right?

In comparison, we have two typical scenarios here

1. Without Input / Output
https://github.com/khoi/SimpleBudget/blob/6a354ec81ec17761e4e4c0ecb7997f29524020bc/SimpleBudget/Scene/AddTransaction/AddTransactionViewModel.swift#L14-L81
2. Introduce Input and Output
https://github.com/khoi/SimpleBudget/blob/b706e5d183aa62cfca589e51d466360b38c3c7c3/SimpleBudget/Scene/AddTransaction/AddTransactionViewModel.swift#L14-L99

**Comment by dangthaison91** [comment]
If you are finding a way to organize your VM, I will prefer this approach:
https://github.com/kickstarter/ios-oss/blob/master/Library/ViewModels/HelpViewModel.swift

This will have a little more boilerplate code but will provide more flexibility once you want to introduce a protocol/interface between VM - VC to make them more loose-coupled.

**Comment by dangthaison91** [comment]
OTW, defining your `Input's` property as `PublishRelay/BehaviorRelay` will help you test VM easier, test code shorter?

**Comment by NghiaTranUIT** [comment]
Yup, I tried this approach from KickstarterOSS and come up the idea from Input / Output Struct rather than protocol.

Personally, both approaches also have trade-offs. There is no one is better the other. It's up to us to choose which one to adopt.

===============

Regarding `PublishRelay/BehaviorRelay` in Input. I don't think it's good idea to expose those internal variables of `ViewModel` to ViewController.

Ideally, all internal states should be isolated in order to avoid modifying them from outside by accidentally or deliberately. Thus, it diminishes the rate of error.

Furthermore, we can easily test the `BehaviorRelay` by passing the Input signal and assessing the output too.

**Comment by khoi** [comment]
> I don't think PublishRelay/BehaviorRelay are internal variable/state. They're used to receive inputs from outside

`Relay` or `Subject` or `Observable` for that matter can be used for anything. There is no rule against using it to maintain internal state nor receiving inputs.

That's being said, after going through the actual implementation in #23. I have to agree that having `Relay` directly as inputs will make the code significantly easier to read.
